### ISSUE TITLE
[Bug] - Hibernate stopped working on 2023.9.20251208

### ISSUE THREAD

**Issue by p24-max** [amazonlinux/amazon-linux-2022#1049]
**Describe the bug**
AL2023 cannot be hibernated anymore with version 2023.9.20251208. I tested it with a new instance using ami-097e0f4a93b046e1a and ami-089dc6fe381a457ca with T4G.micro, both not working.

**To Reproduce**
1. Launch new instance based on ami-097e0f4a93b046e1a with t4g.micro (set `Stop - Hibernate behavior` = `Enabled`)
2. Once instance is up, hibernate from EC2-console
3. Instance is now stuck in "Stopping" state

**Expected behavior**
Instance hibernates successfully like with previous versions of AL2023.

**Additional context**
I tested same with ami-0a617b714486fa084 (al2023-ami-2023.9.20251117.1-kernel-6.12-arm64), there it worked as expected.

**Logs when triggering Hibernate**

`journalctl` on version 2023.9.20251208:
```
Jan 02 14:03:44 ip-10-0-0-76.eu-central-1.compute.internal hibernate[5352]: ACPI action undefined: SBTN
Jan 02 14:03:44 ip-10-0-0-76.eu-central-1.compute.internal hibernate[5354]: ACPI action undefined: PNP0C0E:00
```

`journalctl` on version 2023.9.20251117:
```
Jan 02 14:09:46 ip-10-0-1-27.eu-central-1.compute.internal systemd-logind[1816]: Suspend key pressed short.
Jan 02 14:09:46 ip-10-0-1-27.eu-central-1.compute.internal hibernate[5313]: Got SBTN event, going to hibernate
Jan 02 14:09:46 ip-10-0-1-27.eu-central-1.compute.internal kernel: Adding 4095996k swap on /swap.  Priority:32767 extents:2 across:5373936k SS

Broadcast message from root@localhost (Fri 2026-01-02 14:09:47 UTC):

The system will hibernate now!
```

**Comment by isaacdorfman** [comment]
We also encounter this issue and it gives us big problems.
Help would be appreciated.

**Comment by ozbenh** [comment]
Thanks, forwarded to our kernel team

**Comment by bjoernd** [comment]
We're still investigating a fix, but have tracked this down to a problem with the update of `ec2-hibinit-agent` that was shipped with the 2023.9.20251208 release. For now, you may work around the problem by

```
sudo dnf downgrade ec2-hibinit-agent-1.0.8-0.amzn2023
sudo systemctl restart hibinit-agent
```

**Comment by uaydin-amzn** [comment]
We released the new version of ec2-hibinit-agent please upgrade to the that version:
`ec2-hibinit-agent-1.0.10-1`

**Comment by isaacdorfman** [comment]
> We released the new version of ec2-hibinit-agent please upgrade to the that version: `ec2-hibinit-agent-1.0.10-1`

Amazing!
When is it scheduled to be released inside an AMI?

**Comment by uaydin-amzn** [comment]
You can update or create AMIs with releasever=2023.6.20260120
